<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="media\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="media\real_flowers.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="media\simple_flower.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Tools">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NBitcoin" />
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" />
    <PackageReference Include="Stateless" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SIPSorcery\SIPSorcery.csproj" />
    <ProjectReference Include="..\..\..\src\SIPSorceryMedia.FFmpeg\SIPSorceryMedia.FFmpeg.csproj" />
  </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\lightning.proto" GrpcServices="Client" />
        <Protobuf Include="Protos\invoices.proto" GrpcServices="Client" />
        <Protobuf Include="Protos\router.proto" GrpcServices="Client" />
    </ItemGroup>

</Project>
