// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Renegotiate;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks;
using Cloudflare.Realtime.Sfu.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\sessions\{sessionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSessionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The datachannels property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.DatachannelsRequestBuilder Datachannels
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.DatachannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The renegotiate property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Renegotiate.RenegotiateRequestBuilder Renegotiate
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Renegotiate.RenegotiateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tracks property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.TracksRequestBuilder Tracks
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.TracksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSessionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/{sessionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSessionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/{sessionId}", rawUrl)
        {
        }
        /// <summary>
        /// Return the list of tracks associated to the session
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse>(requestInfo, global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return the list of tracks associated to the session
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
