// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Adapters
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\adapters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdaptersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The websocket property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.WebsocketRequestBuilder Websocket
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.WebsocketRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.AdaptersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdaptersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/adapters", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.AdaptersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdaptersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/adapters", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
