//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SIPSorcery.SIP.App.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SIPSorceryAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SIPSorceryAppEntities object using the connection string found in the 'SIPSorceryAppEntities' section of the application configuration file.
        /// </summary>
        public SIPSorceryAppEntities() : base("name=SIPSorceryAppEntities", "SIPSorceryAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SIPSorceryAppEntities object.
        /// </summary>
        public SIPSorceryAppEntities(string connectionString) : base(connectionString, "SIPSorceryAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SIPSorceryAppEntities object.
        /// </summary>
        public SIPSorceryAppEntities(EntityConnection connection) : base(connection, "SIPSorceryAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIPDialplanLookup> SIPDialplanLookups
        {
            get
            {
                if ((_SIPDialplanLookups == null))
                {
                    _SIPDialplanLookups = base.CreateObjectSet<SIPDialplanLookup>("SIPDialplanLookups");
                }
                return _SIPDialplanLookups;
            }
        }
        private ObjectSet<SIPDialplanLookup> _SIPDialplanLookups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIPDialplanRoute> SIPDialplanRoutes
        {
            get
            {
                if ((_SIPDialplanRoutes == null))
                {
                    _SIPDialplanRoutes = base.CreateObjectSet<SIPDialplanRoute>("SIPDialplanRoutes");
                }
                return _SIPDialplanRoutes;
            }
        }
        private ObjectSet<SIPDialplanRoute> _SIPDialplanRoutes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIPDialplanProvider> SIPDialplanProviders
        {
            get
            {
                if ((_SIPDialplanProviders == null))
                {
                    _SIPDialplanProviders = base.CreateObjectSet<SIPDialplanProvider>("SIPDialplanProviders");
                }
                return _SIPDialplanProviders;
            }
        }
        private ObjectSet<SIPDialplanProvider> _SIPDialplanProviders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SIPDialplanOption> SIPDialplanOptions
        {
            get
            {
                if ((_SIPDialplanOptions == null))
                {
                    _SIPDialplanOptions = base.CreateObjectSet<SIPDialplanOption>("SIPDialplanOptions");
                }
                return _SIPDialplanOptions;
            }
        }
        private ObjectSet<SIPDialplanOption> _SIPDialplanOptions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIPDialplanLookups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIPDialplanLookups(SIPDialplanLookup sIPDialplanLookup)
        {
            base.AddObject("SIPDialplanLookups", sIPDialplanLookup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIPDialplanRoutes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIPDialplanRoutes(SIPDialplanRoute sIPDialplanRoute)
        {
            base.AddObject("SIPDialplanRoutes", sIPDialplanRoute);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIPDialplanProviders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIPDialplanProviders(SIPDialplanProvider sIPDialplanProvider)
        {
            base.AddObject("SIPDialplanProviders", sIPDialplanProvider);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SIPDialplanOptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSIPDialplanOptions(SIPDialplanOption sIPDialplanOption)
        {
            base.AddObject("SIPDialplanOptions", sIPDialplanOption);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="SIPDialplanLookup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIPDialplanLookup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIPDialplanLookup object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="lookupkey">Initial value of the lookupkey property.</param>
        /// <param name="lookuptype">Initial value of the lookuptype property.</param>
        /// <param name="owner">Initial value of the owner property.</param>
        public static SIPDialplanLookup CreateSIPDialplanLookup(global::System.String id, global::System.String lookupkey, global::System.Int32 lookuptype, global::System.String owner)
        {
            SIPDialplanLookup sIPDialplanLookup = new SIPDialplanLookup();
            sIPDialplanLookup.id = id;
            sIPDialplanLookup.lookupkey = lookupkey;
            sIPDialplanLookup.lookuptype = lookuptype;
            sIPDialplanLookup.owner = owner;
            return sIPDialplanLookup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lookupkey
        {
            get
            {
                return _lookupkey;
            }
            set
            {
                OnlookupkeyChanging(value);
                ReportPropertyChanging("lookupkey");
                _lookupkey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lookupkey");
                OnlookupkeyChanged();
            }
        }
        private global::System.String _lookupkey;
        partial void OnlookupkeyChanging(global::System.String value);
        partial void OnlookupkeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lookuptype
        {
            get
            {
                return _lookuptype;
            }
            set
            {
                OnlookuptypeChanging(value);
                ReportPropertyChanging("lookuptype");
                _lookuptype = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lookuptype");
                OnlookuptypeChanged();
            }
        }
        private global::System.Int32 _lookuptype;
        partial void OnlookuptypeChanging(global::System.Int32 value);
        partial void OnlookuptypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lookupvalue
        {
            get
            {
                return _lookupvalue;
            }
            set
            {
                OnlookupvalueChanging(value);
                ReportPropertyChanging("lookupvalue");
                _lookupvalue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lookupvalue");
                OnlookupvalueChanged();
            }
        }
        private global::System.String _lookupvalue;
        partial void OnlookupvalueChanging(global::System.String value);
        partial void OnlookupvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.String _owner;
        partial void OnownerChanging(global::System.String value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dialplanname
        {
            get
            {
                return _dialplanname;
            }
            set
            {
                OndialplannameChanging(value);
                ReportPropertyChanging("dialplanname");
                _dialplanname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dialplanname");
                OndialplannameChanged();
            }
        }
        private global::System.String _dialplanname;
        partial void OndialplannameChanging(global::System.String value);
        partial void OndialplannameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="SIPDialplanOption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIPDialplanOption : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIPDialplanOption object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="owner">Initial value of the owner property.</param>
        /// <param name="enablesafeguards">Initial value of the enablesafeguards property.</param>
        public static SIPDialplanOption CreateSIPDialplanOption(global::System.String id, global::System.String owner, global::System.Boolean enablesafeguards)
        {
            SIPDialplanOption sIPDialplanOption = new SIPDialplanOption();
            sIPDialplanOption.id = id;
            sIPDialplanOption.owner = owner;
            sIPDialplanOption.enablesafeguards = enablesafeguards;
            return sIPDialplanOption;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String allowedcountrycodes
        {
            get
            {
                return _allowedcountrycodes;
            }
            set
            {
                OnallowedcountrycodesChanging(value);
                ReportPropertyChanging("allowedcountrycodes");
                _allowedcountrycodes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("allowedcountrycodes");
                OnallowedcountrycodesChanged();
            }
        }
        private global::System.String _allowedcountrycodes;
        partial void OnallowedcountrycodesChanging(global::System.String value);
        partial void OnallowedcountrycodesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> areacode
        {
            get
            {
                return _areacode;
            }
            set
            {
                OnareacodeChanging(value);
                ReportPropertyChanging("areacode");
                _areacode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("areacode");
                OnareacodeChanged();
            }
        }
        private Nullable<global::System.Int32> _areacode;
        partial void OnareacodeChanging(Nullable<global::System.Int32> value);
        partial void OnareacodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> countrycode
        {
            get
            {
                return _countrycode;
            }
            set
            {
                OncountrycodeChanging(value);
                ReportPropertyChanging("countrycode");
                _countrycode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("countrycode");
                OncountrycodeChanged();
            }
        }
        private Nullable<global::System.Int32> _countrycode;
        partial void OncountrycodeChanging(Nullable<global::System.Int32> value);
        partial void OncountrycodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String enumservers
        {
            get
            {
                return _enumservers;
            }
            set
            {
                OnenumserversChanging(value);
                ReportPropertyChanging("enumservers");
                _enumservers = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("enumservers");
                OnenumserversChanged();
            }
        }
        private global::System.String _enumservers;
        partial void OnenumserversChanging(global::System.String value);
        partial void OnenumserversChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String excludedprefixes
        {
            get
            {
                return _excludedprefixes;
            }
            set
            {
                OnexcludedprefixesChanging(value);
                ReportPropertyChanging("excludedprefixes");
                _excludedprefixes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("excludedprefixes");
                OnexcludedprefixesChanged();
            }
        }
        private global::System.String _excludedprefixes;
        partial void OnexcludedprefixesChanging(global::System.String value);
        partial void OnexcludedprefixesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.String _owner;
        partial void OnownerChanging(global::System.String value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timezone
        {
            get
            {
                return _timezone;
            }
            set
            {
                OntimezoneChanging(value);
                ReportPropertyChanging("timezone");
                _timezone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timezone");
                OntimezoneChanged();
            }
        }
        private global::System.String _timezone;
        partial void OntimezoneChanging(global::System.String value);
        partial void OntimezoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String whitepageskey
        {
            get
            {
                return _whitepageskey;
            }
            set
            {
                OnwhitepageskeyChanging(value);
                ReportPropertyChanging("whitepageskey");
                _whitepageskey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("whitepageskey");
                OnwhitepageskeyChanged();
            }
        }
        private global::System.String _whitepageskey;
        partial void OnwhitepageskeyChanging(global::System.String value);
        partial void OnwhitepageskeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean enablesafeguards
        {
            get
            {
                return _enablesafeguards;
            }
            set
            {
                OnenablesafeguardsChanging(value);
                ReportPropertyChanging("enablesafeguards");
                _enablesafeguards = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enablesafeguards");
                OnenablesafeguardsChanged();
            }
        }
        private global::System.Boolean _enablesafeguards;
        partial void OnenablesafeguardsChanging(global::System.Boolean value);
        partial void OnenablesafeguardsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dialplanname
        {
            get
            {
                return _dialplanname;
            }
            set
            {
                OndialplannameChanging(value);
                ReportPropertyChanging("dialplanname");
                _dialplanname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dialplanname");
                OndialplannameChanged();
            }
        }
        private global::System.String _dialplanname;
        partial void OndialplannameChanging(global::System.String value);
        partial void OndialplannameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="SIPDialplanProvider")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIPDialplanProvider : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIPDialplanProvider object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="owner">Initial value of the owner property.</param>
        /// <param name="providerdialstring">Initial value of the providerdialstring property.</param>
        /// <param name="providername">Initial value of the providername property.</param>
        public static SIPDialplanProvider CreateSIPDialplanProvider(global::System.String id, global::System.String owner, global::System.String providerdialstring, global::System.String providername)
        {
            SIPDialplanProvider sIPDialplanProvider = new SIPDialplanProvider();
            sIPDialplanProvider.id = id;
            sIPDialplanProvider.owner = owner;
            sIPDialplanProvider.providerdialstring = providerdialstring;
            sIPDialplanProvider.providername = providername;
            return sIPDialplanProvider;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.String _owner;
        partial void OnownerChanging(global::System.String value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String providerdescription
        {
            get
            {
                return _providerdescription;
            }
            set
            {
                OnproviderdescriptionChanging(value);
                ReportPropertyChanging("providerdescription");
                _providerdescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("providerdescription");
                OnproviderdescriptionChanged();
            }
        }
        private global::System.String _providerdescription;
        partial void OnproviderdescriptionChanging(global::System.String value);
        partial void OnproviderdescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String providerdialstring
        {
            get
            {
                return _providerdialstring;
            }
            set
            {
                OnproviderdialstringChanging(value);
                ReportPropertyChanging("providerdialstring");
                _providerdialstring = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("providerdialstring");
                OnproviderdialstringChanged();
            }
        }
        private global::System.String _providerdialstring;
        partial void OnproviderdialstringChanging(global::System.String value);
        partial void OnproviderdialstringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String providername
        {
            get
            {
                return _providername;
            }
            set
            {
                OnprovidernameChanging(value);
                ReportPropertyChanging("providername");
                _providername = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("providername");
                OnprovidernameChanged();
            }
        }
        private global::System.String _providername;
        partial void OnprovidernameChanging(global::System.String value);
        partial void OnprovidernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String providerprefix
        {
            get
            {
                return _providerprefix;
            }
            set
            {
                OnproviderprefixChanging(value);
                ReportPropertyChanging("providerprefix");
                _providerprefix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("providerprefix");
                OnproviderprefixChanged();
            }
        }
        private global::System.String _providerprefix;
        partial void OnproviderprefixChanging(global::System.String value);
        partial void OnproviderprefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dialplanname
        {
            get
            {
                return _dialplanname;
            }
            set
            {
                OndialplannameChanging(value);
                ReportPropertyChanging("dialplanname");
                _dialplanname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dialplanname");
                OndialplannameChanged();
            }
        }
        private global::System.String _dialplanname;
        partial void OndialplannameChanging(global::System.String value);
        partial void OndialplannameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="SIPDialplanRoute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIPDialplanRoute : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SIPDialplanRoute object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="owner">Initial value of the owner property.</param>
        /// <param name="routedestination">Initial value of the routedestination property.</param>
        /// <param name="routename">Initial value of the routename property.</param>
        /// <param name="routepattern">Initial value of the routepattern property.</param>
        public static SIPDialplanRoute CreateSIPDialplanRoute(global::System.String id, global::System.String owner, global::System.String routedestination, global::System.String routename, global::System.String routepattern)
        {
            SIPDialplanRoute sIPDialplanRoute = new SIPDialplanRoute();
            sIPDialplanRoute.id = id;
            sIPDialplanRoute.owner = owner;
            sIPDialplanRoute.routedestination = routedestination;
            sIPDialplanRoute.routename = routename;
            sIPDialplanRoute.routepattern = routepattern;
            return sIPDialplanRoute;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.String _owner;
        partial void OnownerChanging(global::System.String value);
        partial void OnownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String routedescription
        {
            get
            {
                return _routedescription;
            }
            set
            {
                OnroutedescriptionChanging(value);
                ReportPropertyChanging("routedescription");
                _routedescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("routedescription");
                OnroutedescriptionChanged();
            }
        }
        private global::System.String _routedescription;
        partial void OnroutedescriptionChanging(global::System.String value);
        partial void OnroutedescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String routedestination
        {
            get
            {
                return _routedestination;
            }
            set
            {
                OnroutedestinationChanging(value);
                ReportPropertyChanging("routedestination");
                _routedestination = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("routedestination");
                OnroutedestinationChanged();
            }
        }
        private global::System.String _routedestination;
        partial void OnroutedestinationChanging(global::System.String value);
        partial void OnroutedestinationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String routename
        {
            get
            {
                return _routename;
            }
            set
            {
                OnroutenameChanging(value);
                ReportPropertyChanging("routename");
                _routename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("routename");
                OnroutenameChanged();
            }
        }
        private global::System.String _routename;
        partial void OnroutenameChanging(global::System.String value);
        partial void OnroutenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String routepattern
        {
            get
            {
                return _routepattern;
            }
            set
            {
                OnroutepatternChanging(value);
                ReportPropertyChanging("routepattern");
                _routepattern = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("routepattern");
                OnroutepatternChanged();
            }
        }
        private global::System.String _routepattern;
        partial void OnroutepatternChanging(global::System.String value);
        partial void OnroutepatternChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dialplanname
        {
            get
            {
                return _dialplanname;
            }
            set
            {
                OndialplannameChanging(value);
                ReportPropertyChanging("dialplanname");
                _dialplanname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dialplanname");
                OndialplannameChanged();
            }
        }
        private global::System.String _dialplanname;
        partial void OndialplannameChanging(global::System.String value);
        partial void OndialplannameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String routeprefix
        {
            get
            {
                return _routeprefix;
            }
            set
            {
                OnrouteprefixChanging(value);
                ReportPropertyChanging("routeprefix");
                _routeprefix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("routeprefix");
                OnrouteprefixChanged();
            }
        }
        private global::System.String _routeprefix;
        partial void OnrouteprefixChanging(global::System.String value);
        partial void OnrouteprefixChanged();

        #endregion
    
    }

    #endregion
    
}
