// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.Close;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.New;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.Update;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\sessions\{sessionId}\tracks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TracksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The close property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.Close.CloseRequestBuilder Close
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.Close.CloseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The new property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.New.NewRequestBuilder New
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.Update.UpdateRequestBuilder Update
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.TracksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TracksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/{sessionId}/tracks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Tracks.TracksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TracksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/{sessionId}/tracks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
