<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SIPSorcery.Cli\SIPSorcery.Cli.csproj" />
    <ProjectReference Include="..\..\src\SIPSorcery.Cli.Common\SIPSorcery.Cli.Common.csproj" />
    <ProjectReference Include="..\..\src\SIPSorcery.Diagnostics\SIPSorcery.Diagnostics.csproj" />
  </ItemGroup>

</Project>
