//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDR
    {
        public CDR()
        {
            this.rtccs = new HashSet<RTCC>();
        }
    
        public string AdminMemberID { get; set; }
        public string AnsweredReason { get; set; }
        public Nullable<int> AnsweredStatus { get; set; }
        public string AnsweredTime { get; set; }
        public string BridgeID { get; set; }
        public string CallID { get; set; }
        public string Created { get; set; }
        public string Direction { get; set; }
        public string Dst { get; set; }
        public string DstHost { get; set; }
        public string DstURI { get; set; }
        public Nullable<int> Duration { get; set; }
        public string FromHeader { get; set; }
        public string FromName { get; set; }
        public string FromUser { get; set; }
        public string HungupReason { get; set; }
        public string HungupTime { get; set; }
        public string ID { get; set; }
        public string InProgressReason { get; set; }
        public Nullable<int> InProgressStatus { get; set; }
        public string InProgressTime { get; set; }
        public string Inserted { get; set; }
        public string LocalSocket { get; set; }
        public string Owner { get; set; }
        public string RemoteSocket { get; set; }
        public Nullable<int> RingDuration { get; set; }
        public Nullable<System.DateTime> AnsweredAt { get; set; }
        public string DialPlanContextID { get; set; }
    
        public virtual ICollection<RTCC> rtccs { get; set; }
    }
}
