//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public string ID { get; set; }
        public string Owner { get; set; }
        public string AccountCode { get; set; }
        public decimal Credit { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> PIN { get; set; }
        public string Inserted { get; set; }
        public int RatePlan { get; set; }
    }
}
