//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPAccount
    {
        public SIPAccount()
        {
            this.sipregistrarbindings = new HashSet<SIPRegistrarBinding>();
        }
    
        public string AdminDisabledReason { get; set; }
        public string AdminMemberID { get; set; }
        public bool DontMangleEnabled { get; set; }
        public string ID { get; set; }
        public string InDialPlanName { get; set; }
        public string Inserted { get; set; }
        public string IPAddressACL { get; set; }
        public bool IsAdminDisabled { get; set; }
        public bool IsIncomingOnly { get; set; }
        public bool IsSwitchboardEnabled { get; set; }
        public bool IsUserDisabled { get; set; }
        public string NetworkID { get; set; }
        public string OutDialPlanName { get; set; }
        public string Owner { get; set; }
        public bool SendNATKeepAlives { get; set; }
        public string SIPDomain { get; set; }
        public string SIPPassword { get; set; }
        public string SIPUsername { get; set; }
        public string AvatarURL { get; set; }
        public string Description { get; set; }
        public string AccountCode { get; set; }
    
        public virtual ICollection<SIPRegistrarBinding> sipregistrarbindings { get; set; }
    }
}
