//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPDialplanRoute
    {
        public string ID { get; set; }
        public string Owner { get; set; }
        public string RouteDescription { get; set; }
        public string RouteDestination { get; set; }
        public string RouteName { get; set; }
        public string RoutePattern { get; set; }
        public string DialPlanID { get; set; }
    
        public virtual SIPDialPlan sipdialplan { get; set; }
    }
}
