//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPDialPlan
    {
        public SIPDialPlan()
        {
            this.sipdialplanlookups = new HashSet<SIPDialplanLookup>();
            this.sipdialplanoptions = new HashSet<SIPDialplanOption>();
            this.sipdialplanproviders = new HashSet<SIPDialplanProvider>();
            this.sipdialplanroutes = new HashSet<SIPDialplanRoute>();
            this.SimpleWizardRules = new HashSet<SimpleWizardRule>();
        }
    
        public string AdminMemberId { get; set; }
        public string AuthorisedApps { get; set; }
        public string DialPlanName { get; set; }
        public string DialPlanScript { get; set; }
        public int ExecutionCount { get; set; }
        public string ID { get; set; }
        public string Inserted { get; set; }
        public string LastUpdate { get; set; }
        public int MaxExecutionCount { get; set; }
        public string Owner { get; set; }
        public string ScriptTypeDescription { get; set; }
        public string TraceEmailAddress { get; set; }
        public bool AcceptNonInvite { get; set; }
        public bool IsReadOnly { get; set; }
    
        public virtual ICollection<SIPDialplanLookup> sipdialplanlookups { get; set; }
        public virtual ICollection<SIPDialplanOption> sipdialplanoptions { get; set; }
        public virtual ICollection<SIPDialplanProvider> sipdialplanproviders { get; set; }
        public virtual ICollection<SIPDialplanRoute> sipdialplanroutes { get; set; }
        public virtual ICollection<SimpleWizardRule> SimpleWizardRules { get; set; }
    }
}
