//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPDialogue
    {
        public string AdminMemberID { get; set; }
        public string BridgeID { get; set; }
        public Nullable<int> CallDurationLimit { get; set; }
        public string CallID { get; set; }
        public string CDRID { get; set; }
        public int CSeq { get; set; }
        public string Direction { get; set; }
        public string HangupAt { get; set; }
        public string ID { get; set; }
        public string Inserted { get; set; }
        public string LocalTag { get; set; }
        public string LocalUserField { get; set; }
        public string Owner { get; set; }
        public string ProxySIPSocket { get; set; }
        public string RemoteSDP { get; set; }
        public string RemoteTag { get; set; }
        public string RemoteTarget { get; set; }
        public string RemoteUserField { get; set; }
        public string RouteSet { get; set; }
        public string SDP { get; set; }
        public string TransferMode { get; set; }
        public string SwitchboardCallerDescription { get; set; }
        public string SwitchboardDescription { get; set; }
        public string SwitchboardLineName { get; set; }
        public string CRMPersonName { get; set; }
        public string CRMCompanyName { get; set; }
        public string CRMPictureURL { get; set; }
        public string SwitchboardOwner { get; set; }
    }
}
