//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIPSorceryEntities : DbContext
    {
        public SIPSorceryEntities()
            : base("name=SIPSorceryEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SIPDialplanLookup> SIPDialplanLookups { get; set; }
        public DbSet<SIPDialplanRoute> SIPDialplanRoutes { get; set; }
        public DbSet<SIPDialplanProvider> SIPDialplanProviders { get; set; }
        public DbSet<SIPDialplanOption> SIPDialplanOptions { get; set; }
        public DbSet<CDR> CDRs { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<SIPAccount> SIPAccounts { get; set; }
        public DbSet<SIPDialogue> SIPDialogues { get; set; }
        public DbSet<SIPDialPlan> SIPDialPlans { get; set; }
        public DbSet<SIPDomain> SIPDomains { get; set; }
        public DbSet<SIPProviderBinding> SIPProviderBindings { get; set; }
        public DbSet<SIPProvider> SIPProviders { get; set; }
        public DbSet<SIPRegistrarBinding> SIPRegistrarBindings { get; set; }
        public DbSet<Rate> Rates { get; set; }
        public DbSet<RTCC> RTCCs1 { get; set; }
        public DbSet<DialPlanDataEntry> DialPlanData { get; set; }
        public DbSet<WebCallback> WebCallbacks { get; set; }
        public DbSet<CustomerAccount> CustomerAccounts { get; set; }
        public DbSet<SimpleWizardRule> SimpleWizardRules { get; set; }
        public DbSet<PayPalIPN> PayPalIPNs { get; set; }
    }
}
