//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSorcery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallback
    {
        public string ID { get; set; }
        public string Owner { get; set; }
        public string DialString1 { get; set; }
        public string DialString2 { get; set; }
        public string Description { get; set; }
        public string Inserted { get; set; }
    }
}
