// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.Close;
using Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\adapters\websocket
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebsocketRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The close property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.Close.CloseRequestBuilder Close
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.Close.CloseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The new property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder New
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.WebsocketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebsocketRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/adapters/websocket", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.WebsocketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebsocketRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/adapters/websocket", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
