// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Use local to ingest media from an external endpoint. Use remote to stream media from an existing WebRTC track.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdapterObject_location
    {
        [EnumMember(Value = "local")]
        #pragma warning disable CS1591
        Local,
        #pragma warning restore CS1591
        [EnumMember(Value = "remote")]
        #pragma warning disable CS1591
        Remote,
        #pragma warning restore CS1591
    }
}
