// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Adapter mode. Use buffer for local adapters and stream for remote adapters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdapterObject_mode
    {
        [EnumMember(Value = "stream")]
        #pragma warning disable CS1591
        Stream,
        #pragma warning restore CS1591
        [EnumMember(Value = "buffer")]
        #pragma warning disable CS1591
        Buffer,
        #pragma warning restore CS1591
    }
}
