// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Codec for incoming media on local adapters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdapterObject_inputCodec
    {
        [EnumMember(Value = "pcm")]
        #pragma warning disable CS1591
        Pcm,
        #pragma warning restore CS1591
    }
}
