// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AdapterObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Unique identifier of the adapter instance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdapterId { get; set; }
#nullable restore
#else
        public string AdapterId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>WebSocket endpoint URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>Codec for incoming media on local adapters.</summary>
        public global::Cloudflare.Realtime.Sfu.Models.AdapterObject_inputCodec? InputCodec { get; set; }
        /// <summary>Use local to ingest media from an external endpoint. Use remote to stream media from an existing WebRTC track.</summary>
        public global::Cloudflare.Realtime.Sfu.Models.AdapterObject_location? Location { get; set; }
        /// <summary>Adapter mode. Use buffer for local adapters and stream for remote adapters.</summary>
        public global::Cloudflare.Realtime.Sfu.Models.AdapterObject_mode? Mode { get; set; }
        /// <summary>Codec for outgoing media on remote adapters. Use pcm for audio or jpeg for video.</summary>
        public global::Cloudflare.Realtime.Sfu.Models.AdapterObject_outputCodec? OutputCodec { get; set; }
        /// <summary>Session ID of the track owner. Required for remote adapters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>Track name to ingest into or stream from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackName { get; set; }
#nullable restore
#else
        public string TrackName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Models.AdapterObject"/> and sets the default values.
        /// </summary>
        public AdapterObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.AdapterObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cloudflare.Realtime.Sfu.Models.AdapterObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Cloudflare.Realtime.Sfu.Models.AdapterObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adapterId", n => { AdapterId = n.GetStringValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "inputCodec", n => { InputCodec = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_inputCodec>(); } },
                { "location", n => { Location = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_location>(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_mode>(); } },
                { "outputCodec", n => { OutputCodec = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_outputCodec>(); } },
                { "sessionId", n => { SessionId = n.GetStringValue(); } },
                { "trackName", n => { TrackName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("adapterId", AdapterId);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_inputCodec>("inputCodec", InputCodec);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_location>("location", Location);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_mode>("mode", Mode);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.AdapterObject_outputCodec>("outputCodec", OutputCodec);
            writer.WriteStringValue("sessionId", SessionId);
            writer.WriteStringValue("trackName", TrackName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
