// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Codec for outgoing media on remote adapters. Use pcm for audio or jpeg for video.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdapterObject_outputCodec
    {
        [EnumMember(Value = "pcm")]
        #pragma warning disable CS1591
        Pcm,
        #pragma warning restore CS1591
        [EnumMember(Value = "jpeg")]
        #pragma warning disable CS1591
        Jpeg,
        #pragma warning restore CS1591
    }
}
