// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Choose local to broadcast into the given dataChannelName. Choose remote to consume a broadcast from someone else</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataChannelObject_location
    {
        [EnumMember(Value = "local")]
        #pragma warning disable CS1591
        Local,
        #pragma warning restore CS1591
        [EnumMember(Value = "remote")]
        #pragma warning disable CS1591
        Remote,
        #pragma warning restore CS1591
    }
}
