// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DataChannelsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dataChannels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse_dataChannels>? DataChannels { get; set; }
#nullable restore
#else
        public List<global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse_dataChannels> DataChannels { get; set; }
#endif
        /// <summary>The errorCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>The errorDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorDescription { get; set; }
#nullable restore
#else
        public string ErrorDescription { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse"/> and sets the default values.
        /// </summary>
        public DataChannelsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dataChannels", n => { DataChannels = n.GetCollectionOfObjectValues<global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse_dataChannels>(global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse_dataChannels.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "errorDescription", n => { ErrorDescription = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Cloudflare.Realtime.Sfu.Models.DataChannelsResponse_dataChannels>("dataChannels", DataChannels);
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteStringValue("errorDescription", ErrorDescription);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
