// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetSessionStateResponse_tracks : global::Cloudflare.Realtime.Sfu.Models.TrackObject, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The status property</summary>
        public global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse_tracks_status? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse_tracks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse_tracks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse_tracks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "status", n => { Status = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse_tracks_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.GetSessionStateResponse_tracks_status>("status", Status);
        }
    }
}
#pragma warning restore CS0618
