// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SessionDescription_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "answer")]
        #pragma warning disable CS1591
        Answer,
        #pragma warning restore CS1591
        [EnumMember(Value = "offer")]
        #pragma warning disable CS1591
        Offer,
        #pragma warning restore CS1591
    }
}
