// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TrackObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Make the associated transceiver bidirectional. This option works only when the SFU generates the offer</summary>
        public bool? BidirectionalMediaStream { get; set; }
        /// <summary>Give a hint to the SFU about the transceiver kind. This is required when the SFU generates the offer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kind { get; set; }
#nullable restore
#else
        public string Kind { get; set; }
#endif
        /// <summary>If you want to share a track, it should be local. If you want to play a track shared by a remote agent, it should be remote</summary>
        public global::Cloudflare.Realtime.Sfu.Models.TrackObject_location? Location { get; set; }
        /// <summary>mid associated to track&apos;s transceiver. It also can be prefixed with \# to reference an existing transceiver by its trackName</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mid { get; set; }
#nullable restore
#else
        public string Mid { get; set; }
#endif
        /// <summary>Session ID of the track owner. It should be set for remote tracks only</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>Simulcast configuration for the track</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast? Simulcast { get; set; }
#nullable restore
#else
        public global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast Simulcast { get; set; }
#endif
        /// <summary>Given name for the track</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackName { get; set; }
#nullable restore
#else
        public string TrackName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Models.TrackObject"/> and sets the default values.
        /// </summary>
        public TrackObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.TrackObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cloudflare.Realtime.Sfu.Models.TrackObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Cloudflare.Realtime.Sfu.Models.TrackObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bidirectionalMediaStream", n => { BidirectionalMediaStream = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetStringValue(); } },
                { "location", n => { Location = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_location>(); } },
                { "mid", n => { Mid = n.GetStringValue(); } },
                { "sessionId", n => { SessionId = n.GetStringValue(); } },
                { "simulcast", n => { Simulcast = n.GetObjectValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast>(global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast.CreateFromDiscriminatorValue); } },
                { "trackName", n => { TrackName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("bidirectionalMediaStream", BidirectionalMediaStream);
            writer.WriteStringValue("kind", Kind);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_location>("location", Location);
            writer.WriteStringValue("mid", Mid);
            writer.WriteStringValue("sessionId", SessionId);
            writer.WriteObjectValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast>("simulcast", Simulcast);
            writer.WriteStringValue("trackName", TrackName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
