// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Controls what happens if there is not enough network resources available to send the preferredRid. &apos;none&apos; means keep sending even if not enough bandwidth, &apos;asciibetical&apos; uses a-z order to determine priority where a is most desirable and z is least desirable.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrackObject_simulcast_priorityOrdering
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "asciibetical")]
        #pragma warning disable CS1591
        Asciibetical,
        #pragma warning restore CS1591
    }
}
