// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>If you want to share a track, it should be local. If you want to play a track shared by a remote agent, it should be remote</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrackObject_location
    {
        [EnumMember(Value = "local")]
        #pragma warning disable CS1591
        Local,
        #pragma warning restore CS1591
        [EnumMember(Value = "remote")]
        #pragma warning disable CS1591
        Remote,
        #pragma warning restore CS1591
    }
}
