// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>Controls what happens when the rid currently being used or preferredRid is no longer being sent by the publisher. &apos;none&apos; means do nothing, &apos;asciibetical&apos; uses the next available layer after sorting the layers a-z.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrackObject_simulcast_ridNotAvailable
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "asciibetical")]
        #pragma warning disable CS1591
        Asciibetical,
        #pragma warning restore CS1591
    }
}
