// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Cloudflare.Realtime.Sfu.Models
{
    /// <summary>
    /// Simulcast configuration for the track
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrackObject_simulcast : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Preferred RID for simulcast streams</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredRid { get; set; }
#nullable restore
#else
        public string PreferredRid { get; set; }
#endif
        /// <summary>Controls what happens if there is not enough network resources available to send the preferredRid. &apos;none&apos; means keep sending even if not enough bandwidth, &apos;asciibetical&apos; uses a-z order to determine priority where a is most desirable and z is least desirable.</summary>
        public global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_priorityOrdering? PriorityOrdering { get; set; }
        /// <summary>Controls what happens when the rid currently being used or preferredRid is no longer being sent by the publisher. &apos;none&apos; means do nothing, &apos;asciibetical&apos; uses the next available layer after sorting the layers a-z.</summary>
        public global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_ridNotAvailable? RidNotAvailable { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast"/> and sets the default values.
        /// </summary>
        public TrackObject_simulcast()
        {
            AdditionalData = new Dictionary<string, object>();
            PriorityOrdering = global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_priorityOrdering.None;
            RidNotAvailable = global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_ridNotAvailable.None;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "preferredRid", n => { PreferredRid = n.GetStringValue(); } },
                { "priorityOrdering", n => { PriorityOrdering = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_priorityOrdering>(); } },
                { "ridNotAvailable", n => { RidNotAvailable = n.GetEnumValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_ridNotAvailable>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("preferredRid", PreferredRid);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_priorityOrdering>("priorityOrdering", PriorityOrdering);
            writer.WriteEnumValue<global::Cloudflare.Realtime.Sfu.Models.TrackObject_simulcast_ridNotAvailable>("ridNotAvailable", RidNotAvailable);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
