//-----------------------------------------------------------------------------
// Filename: dct_unittest.cs
//
// Description: Unit tests for the VP8 forward DCT (encoder side, src/dct.cs).
// Cross-checks the new forward transform bit-exactly against libvpx's C
// reference implementation, and round-trip-checks it against the
// decoder-side inverse transform in idctllm.cs.
//
// The expected reference values were generated by compiling
// libvpx/vp8/encoder/dct.c standalone and feeding it the same input
// vectors used here. Any divergence indicates a bug in the C# port.
//
// Author(s):
// Aaron Clauson (aaron@sipsorcery.com)
//
// History:
// 25 Apr 2026  Aaron Clauson   Created.
//
// License:
// BSD 3-Clause "New" or "Revised" License, see included LICENSE.md file.
//-----------------------------------------------------------------------------

using Xunit;

namespace Vpx.Net.UnitTest
{
    public unsafe class dct_unittest
    {
        // ---------- Forward DCT 4x4 ----------

        /// <summary>
        /// Bit-exact reference test: fdct of an all-zero input must produce
        /// the same coefficient block libvpx produces (which is NOT all zero
        /// — output[1] = 1 because of the rounding constant 14500 in the
        /// first-pass row transform).
        /// </summary>
        [Fact]
        public void Fdct4x4_ZeroInput_MatchesLibvpxReference()
        {
            short[] expected = {
                0, 1, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
            };
            AssertFdctMatches(new short[16], expected);
        }

        /// <summary>
        /// Bit-exact reference test: fdct of a uniform-32 input.
        /// Reference: DC = 256 = 8 * 32 (the 2D scale factor for libvpx's
        /// fdct), output[1] = 1 from the 14500 rounding.
        /// </summary>
        [Fact]
        public void Fdct4x4_Constant32Input_MatchesLibvpxReference()
        {
            short[] input = new short[16];
            for (int i = 0; i < 16; i++) input[i] = 32;
            short[] expected = {
                256, 1, 0, 0,
                  0, 0, 0, 0,
                  0, 0, 0, 0,
                  0, 0, 0, 0,
            };
            AssertFdctMatches(input, expected);
        }

        /// <summary>
        /// Bit-exact reference test: fdct of a small mixed-sign residual
        /// pattern. Expected values captured from a standalone build of
        /// libvpx/vp8/encoder/dct.c with the same input.
        /// </summary>
        [Fact]
        public void Fdct4x4_MixedResidualPattern_MatchesLibvpxReference()
        {
            short[] input = {
                 5, -3,  2, -1,
                 4,  0,  1,  2,
                -2,  3, -4,  5,
                 1, -2,  3, -1,
            };
            short[] expected = {
                 6,  2,  6,  4,
                 3,  6,  5,  6,
                -3,  4, -3, 14,
                -2, -3,  1, -9,
            };
            AssertFdctMatches(input, expected);
        }

        /// <summary>
        /// fdct followed by the existing decoder-side idct must recover the
        /// original residual within the integer-rounding tolerance of the
        /// 4x4 DCT/IDCT pair. Uses prediction = 128 so [0,255] clipping in
        /// vp8_short_idct4x4llm_c does not engage.
        /// </summary>
        [Fact]
        public void Fdct4x4_RoundTripWithIdct_RecoversInputWithinTolerance()
        {
            short[] residual = {
                 5, -3,  2, -1,
                 4,  0,  1,  2,
                -2,  3, -4,  5,
                 1, -2,  3, -1,
            };

            short* input = stackalloc short[16];
            short* coef = stackalloc short[16];
            byte* pred = stackalloc byte[16];
            byte* dst = stackalloc byte[16];

            for (int i = 0; i < 16; i++)
            {
                input[i] = residual[i];
                pred[i] = 128;
                dst[i] = 0;
            }

            dct.vp8_short_fdct4x4_c(input, coef, 8);
            idctllm.vp8_short_idct4x4llm_c(coef, pred, 4, dst, 4);

            for (int i = 0; i < 16; i++)
            {
                int recovered = dst[i] - 128;
                int expected = residual[i];
                int delta = recovered - expected;
                Assert.True(delta >= -2 && delta <= 2,
                    $"Round-trip exceeded tolerance at i={i}: residual={expected}, recovered={recovered}");
            }
        }

        // ---------- 4x4 Walsh-Hadamard ----------

        /// <summary>
        /// Bit-exact reference test: walsh of an all-zero block.
        /// Walsh's rounding doesn't introduce nonzero coefficients for zero
        /// input (unlike fdct), so the result is all zero.
        /// </summary>
        [Fact]
        public void Walsh4x4_ZeroInput_MatchesLibvpxReference()
        {
            AssertWalshMatches(new short[16], new short[16]);
        }

        /// <summary>
        /// Bit-exact reference test: walsh of a defined pattern.
        /// </summary>
        [Fact]
        public void Walsh4x4_Pattern_MatchesLibvpxReference()
        {
            short[] input = {
                 100, -50,  25, -10,
                  80,   0,  15,  20,
                 -20,  30, -40,  50,
                  10, -20,  30, -10,
            };
            short[] expected = {
                 105,  25, 115,  95,
                  75,  55,  85, 165,
                 -30, -20, -10, 160,
                 -20,  10,  40, -50,
            };
            AssertWalshMatches(input, expected);
        }

        // ---------- helpers ----------

        private static void AssertFdctMatches(short[] input, short[] expected)
        {
            short* inP = stackalloc short[16];
            short* outP = stackalloc short[16];
            for (int i = 0; i < 16; i++) inP[i] = input[i];

            dct.vp8_short_fdct4x4_c(inP, outP, 8);

            for (int i = 0; i < 16; i++)
            {
                Assert.True(outP[i] == expected[i],
                    $"fdct mismatch at i={i}: expected={expected[i]}, got={outP[i]}");
            }
        }

        private static void AssertWalshMatches(short[] input, short[] expected)
        {
            short* inP = stackalloc short[16];
            short* outP = stackalloc short[16];
            for (int i = 0; i < 16; i++) inP[i] = input[i];

            dct.vp8_short_walsh4x4_c(inP, outP, 8);

            for (int i = 0; i < 16; i++)
            {
                Assert.True(outP[i] == expected[i],
                    $"walsh mismatch at i={i}: expected={expected[i]}, got={outP[i]}");
            }
        }
    }
}
