// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.Close;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.Establish;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.New;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\sessions\{sessionId}\datachannels
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DatachannelsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The close property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.Close.CloseRequestBuilder Close
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.Close.CloseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The establish property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.Establish.EstablishRequestBuilder Establish
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.Establish.EstablishRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The new property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.New.NewRequestBuilder New
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.DatachannelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatachannelsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/{sessionId}/datachannels", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.Datachannels.DatachannelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DatachannelsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/{sessionId}/datachannels", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
