// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\adapters\websocket\new
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/adapters/websocket/new", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/adapters/websocket/new", rawUrl)
        {
        }
        /// <summary>
        /// Create WebSocket adapter(s) for ingest or stream
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse?> PostAsync(global::Cloudflare.Realtime.Sfu.Models.NewAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse> PostAsync(global::Cloudflare.Realtime.Sfu.Models.NewAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "503", global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse>(requestInfo, global::Cloudflare.Realtime.Sfu.Models.NewAdapterResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create WebSocket adapter(s) for ingest or stream
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Cloudflare.Realtime.Sfu.Models.NewAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Cloudflare.Realtime.Sfu.Models.NewAdapterRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Cloudflare.Realtime.Sfu.Apps.Item.Adapters.Websocket.New.NewRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
