//-----------------------------------------------------------------------------
// Filename: bitstream_unittest.cs
//
// Description: Unit tests for the VP8 keyframe header writer (encoder side,
// src/bitstream.cs). Cross-checks bit-exactly against libvpx's keyframe
// header path, and verifies the produced bytes parse back through the
// existing decoder's frame-tag parser to recover the correct dimensions
// and frame type.
//
// The expected reference bytes were generated by compiling a standalone
// build of the libvpx vp8/encoder/bitstream.c keyframe path and feeding
// it the same configurations used here. Any divergence indicates a bug
// in the C# port.
//
// Author(s):
// Claude Opus 4.7 (Anthropic AI assistant, model: claude-opus-4-7), commissioned by Aaron Clauson
//
// History:
// 25 Apr 2026  Claude          Created.
//
// License:
// BSD 3-Clause "New" or "Revised" License, see included LICENSE.md file.
//-----------------------------------------------------------------------------

using Xunit;

namespace Vpx.Net.UnitTest
{
    public unsafe class bitstream_unittest
    {
        // ---------- Bit-exact reference tests against libvpx ----------

        /// <summary>
        /// 320x240 baseline keyframe, base quantizer 32, all other features
        /// at their defaults.
        /// </summary>
        [Fact]
        public void PackKeyframeHeader_320x240_Q32_Matches_LibvpxReference()
        {
            byte[] expected = new byte[] {
                0xB0, 0x00, 0x00, 0x9D, 0x01, 0x2A, 0x40, 0x01,
                0xF0, 0x00, 0x00, 0x00, 0x40, 0x08, 0x00,
            };
            var cfg = new KeyframeHeaderConfig
            {
                Width = 320, Height = 240, BaseQindex = 32,
            };
            AssertHeaderBytes(cfg, expected);
        }

        /// <summary>
        /// 16x16 keyframe with FilterLevel=10 and BaseQ=64, exercising the
        /// 6-bit filter level and 7-bit qindex literal writes.
        /// </summary>
        [Fact]
        public void PackKeyframeHeader_16x16_Q64_FilterLevel10_Matches_LibvpxReference()
        {
            byte[] expected = new byte[] {
                0xB0, 0x00, 0x00, 0x9D, 0x01, 0x2A, 0x10, 0x00,
                0x10, 0x00, 0x02, 0x80, 0x80, 0x08, 0x00,
            };
            var cfg = new KeyframeHeaderConfig
            {
                Width = 16, Height = 16, BaseQindex = 64, FilterLevel = 10,
            };
            AssertHeaderBytes(cfg, expected);
        }

        /// <summary>
        /// 1280x720 keyframe with non-zero quantizer deltas (negative for
        /// Y1DC, positive for Y2AC), exercising the put_delta_q sign+magnitude
        /// path. The output is one byte longer than the all-zero-deltas case
        /// because two of the five delta-q fields now require additional
        /// magnitude+sign bits.
        /// </summary>
        [Fact]
        public void PackKeyframeHeader_1280x720_WithDeltaQ_Matches_LibvpxReference()
        {
            byte[] expected = new byte[] {
                0xD0, 0x00, 0x00, 0x9D, 0x01, 0x2A, 0x00, 0x05,
                0xD0, 0x02, 0x00, 0x00, 0x29, 0x3A, 0x42, 0x00,
            };
            var cfg = new KeyframeHeaderConfig
            {
                Width = 1280, Height = 720, BaseQindex = 20,
                Y1DcDeltaQ = -3, Y2AcDeltaQ = 2,
            };
            AssertHeaderBytes(cfg, expected);
        }

        // ---------- Round-trip through the existing decoder's frame parser ----------

        /// <summary>
        /// Verifies that the bytes produced by StartKeyframeHeader +
        /// FinishKeyframeFirstPartition parse back through the existing
        /// decoder's uncompressed frame-tag parser as a keyframe with the
        /// correct width and height.
        /// </summary>
        [Fact]
        public void PackKeyframeHeader_RoundTripsThroughFrameTagParser()
        {
            const int width = 640, height = 480;
            byte[] buf = new byte[256];
            BOOL_CODER bc = default;
            int total;
            fixed (byte* p = buf)
            {
                bitstream.StartKeyframeHeader(p, buf.Length,
                    new KeyframeHeaderConfig { Width = width, Height = height, BaseQindex = 32 },
                    ref bc);
                total = bitstream.FinishKeyframeFirstPartition(p, new KeyframeHeaderConfig
                {
                    Width = width, Height = height, BaseQindex = 32,
                }, ref bc);
            }
            Assert.True(total >= 10, "encoded header must be at least the 10-byte uncompressed prefix");

            // Manually unpack the 3-byte frame tag. RFC 6386 §9.1.
            int v = buf[0] | (buf[1] << 8) | (buf[2] << 16);
            int keyFrameFlag = v & 0x1;            // 0 = key
            int version       = (v >> 1) & 0x7;
            int showFrame     = (v >> 4) & 0x1;
            int firstPartitionLength = v >> 5;
            Assert.Equal(0, keyFrameFlag);
            Assert.Equal(0, version);
            Assert.Equal(1, showFrame);
            Assert.Equal(total - 10, firstPartitionLength);

            // Verify the start code at offset 3.
            Assert.Equal(0x9D, buf[3]);
            Assert.Equal(0x01, buf[4]);
            Assert.Equal(0x2A, buf[5]);

            // Width / height stored at bytes 6-7 (little-endian, 14-bit) and 8-9.
            int wPacked = buf[6] | (buf[7] << 8);
            int hPacked = buf[8] | (buf[9] << 8);
            Assert.Equal(width, wPacked & 0x3FFF);
            Assert.Equal(height, hPacked & 0x3FFF);
            Assert.Equal(0, wPacked >> 14);   // horiz scale
            Assert.Equal(0, hPacked >> 14);   // vert scale
        }

        /// <summary>
        /// The compressed-header bits we wrote are also recoverable: feed
        /// them back through the existing decoder's bool reader and check
        /// the first few bits decode as the values we wrote.
        /// </summary>
        [Fact]
        public void PackKeyframeHeader_CompressedFirstPartitionDecodesToInputs()
        {
            byte[] buf = new byte[256];
            BOOL_CODER bc = default;
            var cfg = new KeyframeHeaderConfig
            {
                Width = 640, Height = 480,
                BaseQindex = 24,
                FilterLevel = 7,
                SharpnessLevel = 3,
                FilterType = 1,
                ColorSpace = 0,
                ClampType = 1,
            };
            int total;
            fixed (byte* p = buf)
            {
                bitstream.StartKeyframeHeader(p, buf.Length, cfg, ref bc);
                total = bitstream.FinishKeyframeFirstPartition(p, cfg, ref bc);
            }

            // Start the existing decoder bool reader at byte 10, feeding it
            // the bytes produced by our encoder bool coder.
            BOOL_DECODER br = new BOOL_DECODER();
            // Take a copy because vp8dx_start_decode pins the input pointer.
            byte[] partition = new byte[total - 10 + 8];  // pad for the decoder's lookahead
            System.Array.Copy(buf, 10, partition, 0, total - 10);

            dboolhuff.vp8dx_start_decode(ref br, partition, (uint)partition.Length);

            int colorSpace        = dboolhuff.vp8dx_decode_bool(ref br, 128);
            int clampType         = dboolhuff.vp8dx_decode_bool(ref br, 128);
            int segmentation      = dboolhuff.vp8dx_decode_bool(ref br, 128);
            int filterType        = dboolhuff.vp8dx_decode_bool(ref br, 128);
            int filterLevel       = dboolhuff.vp8_decode_value(ref br, 6);
            int sharpnessLevel    = dboolhuff.vp8_decode_value(ref br, 3);
            int modeRefLfDelta    = dboolhuff.vp8dx_decode_bool(ref br, 128);
            int log2NumPartitions = dboolhuff.vp8_decode_value(ref br, 2);
            int baseQindex        = dboolhuff.vp8_decode_value(ref br, 7);

            Assert.Equal(cfg.ColorSpace,    colorSpace);
            Assert.Equal(cfg.ClampType,     clampType);
            Assert.Equal(0,                 segmentation);   // we always emit 0
            Assert.Equal(cfg.FilterType,    filterType);
            Assert.Equal(cfg.FilterLevel,   filterLevel);
            Assert.Equal(cfg.SharpnessLevel, sharpnessLevel);
            Assert.Equal(0,                 modeRefLfDelta); // we always emit 0
            Assert.Equal(cfg.Log2NumberOfTokenPartitions, log2NumPartitions);
            Assert.Equal(cfg.BaseQindex,    baseQindex);
        }

        // ---------- helper ----------

        private static void AssertHeaderBytes(KeyframeHeaderConfig cfg, byte[] expected)
        {
            byte[] buf = new byte[256];
            BOOL_CODER bc = default;
            int total;
            fixed (byte* p = buf)
            {
                bitstream.StartKeyframeHeader(p, buf.Length, cfg, ref bc);
                total = bitstream.FinishKeyframeFirstPartition(p, cfg, ref bc);
            }
            Assert.Equal(expected.Length, total);
            for (int i = 0; i < expected.Length; i++)
            {
                Assert.True(expected[i] == buf[i],
                    "byte " + i + " mismatch: expected=0x" + expected[i].ToString("x2") + " actual=0x" + buf[i].ToString("x2"));
            }
        }
    }
}
