//-----------------------------------------------------------------------------
// Filename: quantize_unittest.cs
//
// Description: Unit tests for the VP8 forward quantizer (encoder side,
// src/quantize.cs). Cross-checks vp8_regular_quantize_b_arrays bit-exactly
// against libvpx's vp8_regular_quantize_b_c with the same inputs.
//
// The expected reference values were generated by compiling a standalone
// build of the libvpx vp8_regular_quantize_b_c logic and feeding it the
// same input vectors and quant tables. Any divergence indicates a bug in
// the C# port.
//
// Author(s):
// Claude Opus 4.7 (Anthropic AI assistant, model: claude-opus-4-7), commissioned by Aaron Clauson
//
// History:
// 25 Apr 2026  Claude          Created.
//
// License:
// BSD 3-Clause "New" or "Revised" License, see included LICENSE.md file.
//-----------------------------------------------------------------------------

using Vpx.Net;
using Xunit;

namespace Vpx.Net.UnitTest
{
    public unsafe class quantize_unittest
    {
        // Realistic quant-table set produced by libvpx's invert_quant() for
        // dequant = 8 (a moderate quality factor). With these the integer
        // pipeline performs effectively coeff/8 with libvpx-style rounding.
        private static readonly short[] s_zbin       = Repeat16((short)4);
        private static readonly short[] s_zrun_boost = Repeat16((short)0);
        private static readonly short[] s_round      = Repeat16((short)4);
        private static readonly short[] s_quant      = Repeat16((short)1);
        private static readonly short[] s_quant_shift = Repeat16((short)8192);
        private static readonly short[] s_dequant    = Repeat16((short)8);

        private static short[] Repeat16(short v)
        {
            var a = new short[16];
            for (int i = 0; i < 16; i++) a[i] = v;
            return a;
        }

        /// <summary>
        /// All-zero input → all-zero qcoeff/dqcoeff, eob = 0.
        /// </summary>
        [Fact]
        public void Quantize_ZeroInput_MatchesLibvpxReference()
        {
            short[] coeff = new short[16];
            short[] expectedQ = new short[16];
            short[] expectedDq = new short[16];

            int eob = RunQuantize(coeff, out short[] qcoeff, out short[] dqcoeff);

            Assert.Equal(0, eob);
            Assert.Equal(expectedQ, qcoeff);
            Assert.Equal(expectedDq, dqcoeff);
        }

        /// <summary>
        /// Bit-exact reference test: a defined fdct-output-style block.
        /// Reference values from libvpx vp8_regular_quantize_b_c with the
        /// same quant tables.
        /// </summary>
        [Fact]
        public void Quantize_MixedPattern_MatchesLibvpxReference()
        {
            short[] coeff = {
                 6,  2,  6,  4,
                 3,  6,  5,  6,
                -3,  4, -3, 14,
                -2, -3,  1, -9,
            };
            short[] expectedQ = {
                 1,  0,  1,  1,
                 0,  1,  1,  1,
                 0,  1,  0,  2,
                 0,  0,  0, -1,
            };
            short[] expectedDq = {
                 8,  0,  8,  8,
                 0,  8,  8,  8,
                 0,  8,  0, 16,
                 0,  0,  0, -8,
            };

            int eob = RunQuantize(coeff, out short[] qcoeff, out short[] dqcoeff);

            Assert.Equal(16, eob);
            Assert.Equal(expectedQ, qcoeff);
            Assert.Equal(expectedDq, dqcoeff);
        }

        /// <summary>
        /// Bit-exact reference test: a flat-block fdct output (large DC,
        /// tiny AC). The DC coefficient quantizes to 32 (= 256/8), the
        /// AC[1]=1 sits below zbin and rightly gets dropped, so eob = 1.
        /// dqcoeff[0] reconstructs the DC exactly: 32 * 8 = 256.
        /// </summary>
        [Fact]
        public void Quantize_FlatBlock_DcRecoversExactly()
        {
            short[] coeff = { 256, 1, 0, 0,  0,0,0,0,  0,0,0,0,  0,0,0,0 };
            short[] expectedQ = { 32, 0, 0, 0,  0,0,0,0,  0,0,0,0,  0,0,0,0 };
            short[] expectedDq = { 256, 0, 0, 0,  0,0,0,0,  0,0,0,0,  0,0,0,0 };

            int eob = RunQuantize(coeff, out short[] qcoeff, out short[] dqcoeff);

            Assert.Equal(1, eob);
            Assert.Equal(expectedQ, qcoeff);
            Assert.Equal(expectedDq, dqcoeff);
        }

        /// <summary>
        /// Non-zero <c>zrun_zbin_boost</c> table: still bit-identical to scalar widening-only reference.
        /// </summary>
        [Fact]
        public void Quantize_NonUniformZrunBoost_MatchesScalarReference()
        {
            short[] coeff;
            short[] zbin = Repeat16((short)4);
            short[] zboost = new short[16];
            for (int i = 0; i < 16; i++)
                zboost[i] = (short)(i * 3);
            short[] round = Repeat16((short)4);
            short[] quant = Repeat16((short)1);
            short[] quantShift = Repeat16((short)8192);
            short[] dequant = Repeat16((short)8);

            var rng = new System.Random(321);
            for (int t = 0; t < 64; t++)
            {
                coeff = new short[16];
                for (int i = 0; i < 16; i++)
                    coeff[i] = (short)rng.Next(-120, 121);

                int eSimd = RunQuantizeTables(coeff, zbin, zboost, round, quant, quantShift, dequant, out short[] qS, out short[] dqS);
                int eRef = RunQuantizeTablesScalarRef(coeff, zbin, zboost, round, quant, quantShift, dequant, out short[] qR, out short[] dqR);

                Assert.Equal(eRef, eSimd);
                Assert.Equal(qR, qS);
                Assert.Equal(dqR, dqS);
            }
        }

        // ---------- helpers ----------

        private static int RunQuantizeTables(
            short[] coeff, short[] zbin, short[] zrunBoost, short[] round, short[] quant, short[] quantShift, short[] dequant,
            out short[] qcoeff, out short[] dqcoeff)
        {
            qcoeff = new short[16];
            dqcoeff = new short[16];

            fixed (short* coefP = coeff)
            fixed (short* zbinP = zbin)
            fixed (short* zboostP = zrunBoost)
            fixed (short* roundP = round)
            fixed (short* quantP = quant)
            fixed (short* quantShiftP = quantShift)
            fixed (short* dequantP = dequant)
            fixed (short* qcoeffP = qcoeff)
            fixed (short* dqcoeffP = dqcoeff)
            {
                return quantize.vp8_regular_quantize_b_arrays(
                    coefP, zbinP, zboostP, roundP, quantP, quantShiftP, dequantP,
                    qcoeffP, dqcoeffP, zbin_extra: 0);
            }
        }

        /// <summary>Pure C# duplicate of the quantize loop (no SIMD in widen/clear) for regression checks.</summary>
        private static int RunQuantizeTablesScalarRef(
            short[] coeff, short[] zbin, short[] zrunBoost, short[] round, short[] quant, short[] quantShift, short[] dequant,
            out short[] qcoeff, out short[] dqcoeff)
        {
            qcoeff = new short[16];
            dqcoeff = new short[16];
            for (int i = 0; i < 16; i++)
            {
                qcoeff[i] = 0;
                dqcoeff[i] = 0;
            }

            int eob = -1;
            int zbin_boost_idx = 0;
            int[] coeff32 = new int[16];
            for (int j = 0; j < 16; j++)
                coeff32[j] = coeff[j];

            for (int i = 0; i < 16; ++i)
            {
                int rc = entropy.vp8_default_zig_zag1d[i];
                int z = coeff32[rc];

                int zbin_thr = zbin[rc] + zrunBoost[zbin_boost_idx] + 0;
                zbin_boost_idx++;

                int sz = (z >> 31);
                int x = (z ^ sz) - sz;

                if (x >= zbin_thr)
                {
                    x += round[rc];
                    int y = ((((x * quant[rc]) >> 16) + x) * quantShift[rc]) >> 16;
                    x = (y ^ sz) - sz;
                    qcoeff[rc] = (short)x;
                    dqcoeff[rc] = (short)(x * dequant[rc]);

                    if (y != 0)
                    {
                        eob = i;
                        zbin_boost_idx = 0;
                    }
                }
            }

            return eob + 1;
        }

        private static int RunQuantize(short[] coeff, out short[] qcoeff, out short[] dqcoeff)
        {
            qcoeff = new short[16];
            dqcoeff = new short[16];

            fixed (short* coefP = coeff)
            fixed (short* zbinP = s_zbin)
            fixed (short* zboostP = s_zrun_boost)
            fixed (short* roundP = s_round)
            fixed (short* quantP = s_quant)
            fixed (short* quantShiftP = s_quant_shift)
            fixed (short* dequantP = s_dequant)
            fixed (short* qcoeffP = qcoeff)
            fixed (short* dqcoeffP = dqcoeff)
            {
                return quantize.vp8_regular_quantize_b_arrays(
                    coefP, zbinP, zboostP, roundP, quantP, quantShiftP, dequantP,
                    qcoeffP, dqcoeffP, zbin_extra: 0);
            }
        }
    }
}
