// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\sessions\new
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/new{?correlationId*,thirdparty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions/new{?correlationId*,thirdparty*}", rawUrl)
        {
        }
        /// <summary>
        /// Create a new PeerConnection
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Models.NewSessionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Cloudflare.Realtime.Sfu.Models.NewSessionResponse?> PostAsync(Action<RequestConfiguration<global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder.NewRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Cloudflare.Realtime.Sfu.Models.NewSessionResponse> PostAsync(Action<RequestConfiguration<global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder.NewRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Cloudflare.Realtime.Sfu.Models.NewSessionResponse>(requestInfo, global::Cloudflare.Realtime.Sfu.Models.NewSessionResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new PeerConnection
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder.NewRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder.NewRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Create a new PeerConnection
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NewRequestBuilderPostQueryParameters 
        {
            /// <summary>Associate session to an user-provided correlation id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("correlationId")]
            public string? CorrelationId { get; set; }
#nullable restore
#else
            [QueryParameter("correlationId")]
            public string CorrelationId { get; set; }
#endif
            /// <summary>Session is intended to connect to an ICE-lite peer like a third party SFU/server</summary>
            [QueryParameter("thirdparty")]
            public bool? Thirdparty { get; set; }
        }
    }
}
#pragma warning restore CS0618
