// <auto-generated/>
#pragma warning disable CS0618
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item;
using Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Cloudflare.Realtime.Sfu.Apps.Item.Sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appId}\sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The new property</summary>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder New
        {
            get => new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Cloudflare.Realtime.Sfu.apps.item.sessions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder"/></returns>
        public global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sessionId", position);
                return new global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.Item.WithSessionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Cloudflare.Realtime.Sfu.Apps.Item.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appId}/sessions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
