name: sipsorcery-core31-win

on:
  push:
    branches:
      - master
      - fixtests
      
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Unit tests
      #run: dotnet test src/SIPSorcery.sln --framework netcoreapp3.1 -c Release --filter "Category!=IPv6&Category!=transport&Category!=txintegration"
      #run: dotnet test src/SIPSorcery.sln --framework netcoreapp3.1 -c Release
      run: dotnet test test/unit/SIPSorcery.UnitTests.csproj
